// <auto-generated />
using System;
using Covid19_Services_Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid19_Services_Backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210526085545_addtestcases")]
    partial class addtestcases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Covid19_Services_Backend.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfCases")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("CaseId");

                    b.HasIndex("CountryId");

                    b.HasIndex("StatusId");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            CaseId = 1,
                            CountryId = 1,
                            Date = new DateTime(2021, 5, 26, 12, 55, 44, 362, DateTimeKind.Local).AddTicks(3940),
                            Lat = 1.2,
                            Lon = 1.3,
                            NumberOfCases = 5,
                            StatusId = 1
                        },
                        new
                        {
                            CaseId = 2,
                            CountryId = 1,
                            Date = new DateTime(2021, 5, 26, 12, 55, 44, 362, DateTimeKind.Local).AddTicks(7212),
                            Lat = 1.2,
                            Lon = 1.3,
                            NumberOfCases = 15,
                            StatusId = 2
                        },
                        new
                        {
                            CaseId = 3,
                            CountryId = 2,
                            Date = new DateTime(2021, 5, 26, 12, 55, 44, 362, DateTimeKind.Local).AddTicks(7383),
                            Lat = 1.2,
                            Lon = 1.3,
                            NumberOfCases = 5,
                            StatusId = 1
                        },
                        new
                        {
                            CaseId = 4,
                            CountryId = 5,
                            Date = new DateTime(2021, 5, 26, 12, 55, 44, 362, DateTimeKind.Local).AddTicks(7408),
                            Lat = 1.2,
                            Lon = 1.3,
                            NumberOfCases = 35,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("Covid19_Services_Backend.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryCode = "LI",
                            Name = "Liechtenstein",
                            Slug = "liechtenstein"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryCode = "NC",
                            Name = "New Caledonia",
                            Slug = "new-caledonia"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryCode = "UA",
                            Name = "Ukraine",
                            Slug = "ukraine"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryCode = "UM",
                            Name = "US Minor Outlying Islands",
                            Slug = "us-minor-outlying-islands"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryCode = "KY",
                            Name = "Cayman Islands",
                            Slug = "cayman-islands"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryCode = "GE",
                            Name = "Georgia",
                            Slug = "georgia"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryCode = "KP",
                            Name = "Korea (North)",
                            Slug = "korea-north"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryCode = "ML",
                            Name = "Mali",
                            Slug = "mali"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryCode = "ST",
                            Name = "Sao Tome and Principe",
                            Slug = "sao-tome-and-principe"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryCode = "TC",
                            Name = "Turks and Caicos Islands",
                            Slug = "turks-and-caicos-islands"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryCode = "AQ",
                            Name = "Antarctica",
                            Slug = "antarctica"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryCode = "BO",
                            Name = "Bolivia",
                            Slug = "bolivia"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryCode = "GM",
                            Name = "Gambia",
                            Slug = "gambia"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryCode = "JO",
                            Name = "Jordan",
                            Slug = "jordan"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryCode = "MY",
                            Name = "Malaysia",
                            Slug = "malaysia"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryCode = "PS",
                            Name = "Palestinian Territory",
                            Slug = "palestine"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryCode = "SJ",
                            Name = "Svalbard and Jan Mayen Islands",
                            Slug = "svalbard-and-jan-mayen-islands"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryCode = "TJ",
                            Name = "Tajikistan",
                            Slug = "tajikistan"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryCode = "TZ",
                            Name = "Tanzania, United Republic of",
                            Slug = "tanzania"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryCode = "ZW",
                            Name = "Zimbabwe",
                            Slug = "zimbabwe"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryCode = "AF",
                            Name = "Afghanistan",
                            Slug = "afghanistan"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryCode = "KG",
                            Name = "Kyrgyzstan",
                            Slug = "kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryCode = "MV",
                            Name = "Maldives",
                            Slug = "maldives"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryCode = "AM",
                            Name = "Armenia",
                            Slug = "armenia"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryCode = "MR",
                            Name = "Mauritania",
                            Slug = "mauritania"
                        },
                        new
                        {
                            CountryId = 26,
                            CountryCode = "ME",
                            Name = "Montenegro",
                            Slug = "montenegro"
                        },
                        new
                        {
                            CountryId = 27,
                            CountryCode = "WF",
                            Name = "Wallis and Futuna Islands",
                            Slug = "wallis-and-futuna-islands"
                        },
                        new
                        {
                            CountryId = 28,
                            CountryCode = "MD",
                            Name = "Moldova",
                            Slug = "moldova"
                        },
                        new
                        {
                            CountryId = 29,
                            CountryCode = "PW",
                            Name = "Palau",
                            Slug = "palau"
                        },
                        new
                        {
                            CountryId = 30,
                            CountryCode = "TD",
                            Name = "Chad",
                            Slug = "chad"
                        },
                        new
                        {
                            CountryId = 31,
                            CountryCode = "IQ",
                            Name = "Iraq",
                            Slug = "iraq"
                        },
                        new
                        {
                            CountryId = 32,
                            CountryCode = "LS",
                            Name = "Lesotho",
                            Slug = "lesotho"
                        },
                        new
                        {
                            CountryId = 33,
                            CountryCode = "MU",
                            Name = "Mauritius",
                            Slug = "mauritius"
                        },
                        new
                        {
                            CountryId = 34,
                            CountryCode = "IO",
                            Name = "British Indian Ocean Territory",
                            Slug = "british-indian-ocean-territory"
                        },
                        new
                        {
                            CountryId = 35,
                            CountryCode = "CG",
                            Name = "Congo (Brazzaville)",
                            Slug = "congo-brazzaville"
                        },
                        new
                        {
                            CountryId = 36,
                            CountryCode = "SB",
                            Name = "Solomon Islands",
                            Slug = "solomon-islands"
                        },
                        new
                        {
                            CountryId = 37,
                            CountryCode = "TR",
                            Name = "Turkey",
                            Slug = "turkey"
                        },
                        new
                        {
                            CountryId = 38,
                            CountryCode = "EC",
                            Name = "Ecuador",
                            Slug = "ecuador"
                        },
                        new
                        {
                            CountryId = 39,
                            CountryCode = "MT",
                            Name = "Malta",
                            Slug = "malta"
                        },
                        new
                        {
                            CountryId = 40,
                            CountryCode = "PG",
                            Name = "Papua New Guinea",
                            Slug = "papua-new-guinea"
                        },
                        new
                        {
                            CountryId = 41,
                            CountryCode = "PH",
                            Name = "Philippines",
                            Slug = "philippines"
                        },
                        new
                        {
                            CountryId = 42,
                            CountryCode = "TM",
                            Name = "Turkmenistan",
                            Slug = "turkmenistan"
                        },
                        new
                        {
                            CountryId = 43,
                            CountryCode = "VI",
                            Name = "Virgin Islands, US",
                            Slug = "virgin-islands"
                        },
                        new
                        {
                            CountryId = 44,
                            CountryCode = "KM",
                            Name = "Comoros",
                            Slug = "comoros"
                        },
                        new
                        {
                            CountryId = 45,
                            CountryCode = "ZA",
                            Name = "South Africa",
                            Slug = "south-africa"
                        },
                        new
                        {
                            CountryId = 46,
                            CountryCode = "NR",
                            Name = "Nauru",
                            Slug = "nauru"
                        },
                        new
                        {
                            CountryId = 47,
                            CountryCode = "AW",
                            Name = "Aruba",
                            Slug = "aruba"
                        },
                        new
                        {
                            CountryId = 48,
                            CountryCode = "BN",
                            Name = "Brunei Darussalam",
                            Slug = "brunei"
                        },
                        new
                        {
                            CountryId = 49,
                            CountryCode = "CC",
                            Name = "Cocos (Keeling) Islands",
                            Slug = "cocos-keeling-islands"
                        },
                        new
                        {
                            CountryId = 50,
                            CountryCode = "DE",
                            Name = "Germany",
                            Slug = "germany"
                        },
                        new
                        {
                            CountryId = 51,
                            CountryCode = "VA",
                            Name = "Holy See (Vatican City State)",
                            Slug = "holy-see-vatican-city-state"
                        },
                        new
                        {
                            CountryId = 52,
                            CountryCode = "IL",
                            Name = "Israel",
                            Slug = "israel"
                        },
                        new
                        {
                            CountryId = 53,
                            CountryCode = "SG",
                            Name = "Singapore",
                            Slug = "singapore"
                        },
                        new
                        {
                            CountryId = 54,
                            CountryCode = "CN",
                            Name = "China",
                            Slug = "china"
                        },
                        new
                        {
                            CountryId = 55,
                            CountryCode = "HU",
                            Name = "Hungary",
                            Slug = "hungary"
                        },
                        new
                        {
                            CountryId = 56,
                            CountryCode = "IN",
                            Name = "India",
                            Slug = "india"
                        },
                        new
                        {
                            CountryId = 57,
                            CountryCode = "LU",
                            Name = "Luxembourg",
                            Slug = "luxembourg"
                        },
                        new
                        {
                            CountryId = 58,
                            CountryCode = "SM",
                            Name = "San Marino",
                            Slug = "san-marino"
                        },
                        new
                        {
                            CountryId = 59,
                            CountryCode = "KH",
                            Name = "Cambodia",
                            Slug = "cambodia"
                        },
                        new
                        {
                            CountryId = 60,
                            CountryCode = "AX",
                            Name = "ALA Aland Islands",
                            Slug = "ala-aland-islands"
                        },
                        new
                        {
                            CountryId = 61,
                            CountryCode = "BE",
                            Name = "Belgium",
                            Slug = "belgium"
                        },
                        new
                        {
                            CountryId = 62,
                            CountryCode = "BJ",
                            Name = "Benin",
                            Slug = "benin"
                        },
                        new
                        {
                            CountryId = 63,
                            CountryCode = "IR",
                            Name = "Iran, Islamic Republic of",
                            Slug = "iran"
                        },
                        new
                        {
                            CountryId = 64,
                            CountryCode = "MC",
                            Name = "Monaco",
                            Slug = "monaco"
                        },
                        new
                        {
                            CountryId = 65,
                            CountryCode = "PN",
                            Name = "Pitcairn",
                            Slug = "pitcairn"
                        },
                        new
                        {
                            CountryId = 66,
                            CountryCode = "DM",
                            Name = "Dominica",
                            Slug = "dominica"
                        },
                        new
                        {
                            CountryId = 67,
                            CountryCode = "JM",
                            Name = "Jamaica",
                            Slug = "jamaica"
                        },
                        new
                        {
                            CountryId = 68,
                            CountryCode = "LY",
                            Name = "Libya",
                            Slug = "libya"
                        },
                        new
                        {
                            CountryId = 69,
                            CountryCode = "MO",
                            Name = "Macao, SAR China",
                            Slug = "macao-sar-china"
                        },
                        new
                        {
                            CountryId = 70,
                            CountryCode = "TG",
                            Name = "Togo",
                            Slug = "togo"
                        },
                        new
                        {
                            CountryId = 71,
                            CountryCode = "UG",
                            Name = "Uganda",
                            Slug = "uganda"
                        },
                        new
                        {
                            CountryId = 72,
                            CountryCode = "BR",
                            Name = "Brazil",
                            Slug = "brazil"
                        },
                        new
                        {
                            CountryId = 73,
                            CountryCode = "KW",
                            Name = "Kuwait",
                            Slug = "kuwait"
                        },
                        new
                        {
                            CountryId = 74,
                            CountryCode = "LV",
                            Name = "Latvia",
                            Slug = "latvia"
                        },
                        new
                        {
                            CountryId = 75,
                            CountryCode = "MZ",
                            Name = "Mozambique",
                            Slug = "mozambique"
                        },
                        new
                        {
                            CountryId = 76,
                            CountryCode = "SY",
                            Name = "Syrian Arab Republic (Syria)",
                            Slug = "syria"
                        },
                        new
                        {
                            CountryId = 77,
                            CountryCode = "VN",
                            Name = "Viet Nam",
                            Slug = "vietnam"
                        },
                        new
                        {
                            CountryId = 78,
                            CountryCode = "AS",
                            Name = "American Samoa",
                            Slug = "american-samoa"
                        },
                        new
                        {
                            CountryId = 79,
                            CountryCode = "KZ",
                            Name = "Kazakhstan",
                            Slug = "kazakhstan"
                        },
                        new
                        {
                            CountryId = 80,
                            CountryCode = "NZ",
                            Name = "New Zealand",
                            Slug = "new-zealand"
                        },
                        new
                        {
                            CountryId = 81,
                            CountryCode = "SH",
                            Name = "Saint Helena",
                            Slug = "saint-helena"
                        },
                        new
                        {
                            CountryId = 82,
                            CountryCode = "IE",
                            Name = "Ireland",
                            Slug = "ireland"
                        },
                        new
                        {
                            CountryId = 83,
                            CountryCode = "BV",
                            Name = "Bouvet Island",
                            Slug = "bouvet-island"
                        },
                        new
                        {
                            CountryId = 84,
                            CountryCode = "GQ",
                            Name = "Equatorial Guinea",
                            Slug = "equatorial-guinea"
                        },
                        new
                        {
                            CountryId = 85,
                            CountryCode = "GI",
                            Name = "Gibraltar",
                            Slug = "gibraltar"
                        },
                        new
                        {
                            CountryId = 86,
                            CountryCode = "GW",
                            Name = "Guinea-Bissau",
                            Slug = "guinea-bissau"
                        },
                        new
                        {
                            CountryId = 87,
                            CountryCode = "GY",
                            Name = "Guyana",
                            Slug = "guyana"
                        },
                        new
                        {
                            CountryId = 88,
                            CountryCode = "FM",
                            Name = "Micronesia, Federated States of",
                            Slug = "micronesia"
                        },
                        new
                        {
                            CountryId = 89,
                            CountryCode = "BG",
                            Name = "Bulgaria",
                            Slug = "bulgaria"
                        },
                        new
                        {
                            CountryId = 90,
                            CountryCode = "HR",
                            Name = "Croatia",
                            Slug = "croatia"
                        },
                        new
                        {
                            CountryId = 91,
                            CountryCode = "PF",
                            Name = "French Polynesia",
                            Slug = "french-polynesia"
                        },
                        new
                        {
                            CountryId = 92,
                            CountryCode = "GP",
                            Name = "Guadeloupe",
                            Slug = "guadeloupe"
                        },
                        new
                        {
                            CountryId = 93,
                            CountryCode = "GN",
                            Name = "Guinea",
                            Slug = "guinea"
                        },
                        new
                        {
                            CountryId = 94,
                            CountryCode = "HN",
                            Name = "Honduras",
                            Slug = "honduras"
                        },
                        new
                        {
                            CountryId = 95,
                            CountryCode = "QA",
                            Name = "Qatar",
                            Slug = "qatar"
                        },
                        new
                        {
                            CountryId = 96,
                            CountryCode = "RS",
                            Name = "Serbia",
                            Slug = "serbia"
                        },
                        new
                        {
                            CountryId = 97,
                            CountryCode = "TN",
                            Name = "Tunisia",
                            Slug = "tunisia"
                        },
                        new
                        {
                            CountryId = 98,
                            CountryCode = "BF",
                            Name = "Burkina Faso",
                            Slug = "burkina-faso"
                        },
                        new
                        {
                            CountryId = 99,
                            CountryCode = "AL",
                            Name = "Albania",
                            Slug = "albania"
                        },
                        new
                        {
                            CountryId = 100,
                            CountryCode = "EE",
                            Name = "Estonia",
                            Slug = "estonia"
                        },
                        new
                        {
                            CountryId = 101,
                            CountryCode = "NP",
                            Name = "Nepal",
                            Slug = "nepal"
                        },
                        new
                        {
                            CountryId = 102,
                            CountryCode = "SS",
                            Name = "South Sudan",
                            Slug = "south-sudan"
                        },
                        new
                        {
                            CountryId = 103,
                            CountryCode = "BH",
                            Name = "Bahrain",
                            Slug = "bahrain"
                        },
                        new
                        {
                            CountryId = 104,
                            CountryCode = "US",
                            Name = "United States of America",
                            Slug = "united-states"
                        },
                        new
                        {
                            CountryId = 105,
                            CountryCode = "DJ",
                            Name = "Djibouti",
                            Slug = "djibouti"
                        },
                        new
                        {
                            CountryId = 106,
                            CountryCode = "FI",
                            Name = "Finland",
                            Slug = "finland"
                        },
                        new
                        {
                            CountryId = 107,
                            CountryCode = "SE",
                            Name = "Sweden",
                            Slug = "sweden"
                        },
                        new
                        {
                            CountryId = 108,
                            CountryCode = "EH",
                            Name = "Western Sahara",
                            Slug = "western-sahara"
                        },
                        new
                        {
                            CountryId = 109,
                            CountryCode = "ZM",
                            Name = "Zambia",
                            Slug = "zambia"
                        },
                        new
                        {
                            CountryId = 110,
                            CountryCode = "WS",
                            Name = "Samoa",
                            Slug = "samoa"
                        },
                        new
                        {
                            CountryId = 111,
                            CountryCode = "JP",
                            Name = "Japan",
                            Slug = "japan"
                        },
                        new
                        {
                            CountryId = 112,
                            CountryCode = "GR",
                            Name = "Greece",
                            Slug = "greece"
                        },
                        new
                        {
                            CountryId = 113,
                            CountryCode = "AI",
                            Name = "Anguilla",
                            Slug = "anguilla"
                        },
                        new
                        {
                            CountryId = 114,
                            CountryCode = "CO",
                            Name = "Colombia",
                            Slug = "colombia"
                        },
                        new
                        {
                            CountryId = 115,
                            CountryCode = "CY",
                            Name = "Cyprus",
                            Slug = "cyprus"
                        },
                        new
                        {
                            CountryId = 116,
                            CountryCode = "KE",
                            Name = "Kenya",
                            Slug = "kenya"
                        },
                        new
                        {
                            CountryId = 117,
                            CountryCode = "LK",
                            Name = "Sri Lanka",
                            Slug = "sri-lanka"
                        },
                        new
                        {
                            CountryId = 118,
                            CountryCode = "TL",
                            Name = "Timor-Leste",
                            Slug = "timor-leste"
                        },
                        new
                        {
                            CountryId = 119,
                            CountryCode = "BB",
                            Name = "Barbados",
                            Slug = "barbados"
                        },
                        new
                        {
                            CountryId = 120,
                            CountryCode = "CA",
                            Name = "Canada",
                            Slug = "canada"
                        },
                        new
                        {
                            CountryId = 121,
                            CountryCode = "GT",
                            Name = "Guatemala",
                            Slug = "guatemala"
                        },
                        new
                        {
                            CountryId = 122,
                            CountryCode = "FO",
                            Name = "Faroe Islands",
                            Slug = "faroe-islands"
                        },
                        new
                        {
                            CountryId = 123,
                            CountryCode = "MK",
                            Name = "Macedonia, Republic of",
                            Slug = "macedonia"
                        },
                        new
                        {
                            CountryId = 124,
                            CountryCode = "SD",
                            Name = "Sudan",
                            Slug = "sudan"
                        },
                        new
                        {
                            CountryId = 125,
                            CountryCode = "OM",
                            Name = "Oman",
                            Slug = "oman"
                        },
                        new
                        {
                            CountryId = 126,
                            CountryCode = "GF",
                            Name = "French Guiana",
                            Slug = "french-guiana"
                        },
                        new
                        {
                            CountryId = 127,
                            CountryCode = "GA",
                            Name = "Gabon",
                            Slug = "gabon"
                        },
                        new
                        {
                            CountryId = 128,
                            CountryCode = "MG",
                            Name = "Madagascar",
                            Slug = "madagascar"
                        },
                        new
                        {
                            CountryId = 129,
                            CountryCode = "SL",
                            Name = "Sierra Leone",
                            Slug = "sierra-leone"
                        },
                        new
                        {
                            CountryId = 130,
                            CountryCode = "SR",
                            Name = "Suriname",
                            Slug = "suriname"
                        },
                        new
                        {
                            CountryId = 131,
                            CountryCode = "CD",
                            Name = "Congo (Kinshasa)",
                            Slug = "congo-kinshasa"
                        },
                        new
                        {
                            CountryId = 132,
                            CountryCode = "CU",
                            Name = "Cuba",
                            Slug = "cuba"
                        },
                        new
                        {
                            CountryId = 133,
                            CountryCode = "PM",
                            Name = "Saint Pierre and Miquelon",
                            Slug = "saint-pierre-and-miquelon"
                        },
                        new
                        {
                            CountryId = 134,
                            CountryCode = "BY",
                            Name = "Belarus",
                            Slug = "belarus"
                        },
                        new
                        {
                            CountryId = 135,
                            CountryCode = "BW",
                            Name = "Botswana",
                            Slug = "botswana"
                        },
                        new
                        {
                            CountryId = 136,
                            CountryCode = "BI",
                            Name = "Burundi",
                            Slug = "burundi"
                        },
                        new
                        {
                            CountryId = 137,
                            CountryCode = "ER",
                            Name = "Eritrea",
                            Slug = "eritrea"
                        },
                        new
                        {
                            CountryId = 138,
                            CountryCode = "FJ",
                            Name = "Fiji",
                            Slug = "fiji"
                        },
                        new
                        {
                            CountryId = 139,
                            CountryCode = "LT",
                            Name = "Lithuania",
                            Slug = "lithuania"
                        },
                        new
                        {
                            CountryId = 140,
                            CountryCode = "MP",
                            Name = "Northern Mariana Islands",
                            Slug = "northern-mariana-islands"
                        },
                        new
                        {
                            CountryId = 141,
                            CountryCode = "VC",
                            Name = "Saint Vincent and Grenadines",
                            Slug = "saint-vincent-and-the-grenadines"
                        },
                        new
                        {
                            CountryId = 142,
                            CountryCode = "BT",
                            Name = "Bhutan",
                            Slug = "bhutan"
                        },
                        new
                        {
                            CountryId = 143,
                            CountryCode = "TH",
                            Name = "Thailand",
                            Slug = "thailand"
                        },
                        new
                        {
                            CountryId = 144,
                            CountryCode = "BZ",
                            Name = "Belize",
                            Slug = "belize"
                        },
                        new
                        {
                            CountryId = 145,
                            CountryCode = "CF",
                            Name = "Central African Republic",
                            Slug = "central-african-republic"
                        },
                        new
                        {
                            CountryId = 146,
                            CountryCode = "XK",
                            Name = "Republic of Kosovo",
                            Slug = "kosovo"
                        },
                        new
                        {
                            CountryId = 147,
                            CountryCode = "AO",
                            Name = "Angola",
                            Slug = "angola"
                        },
                        new
                        {
                            CountryId = 148,
                            CountryCode = "FK",
                            Name = "Falkland Islands (Malvinas)",
                            Slug = "falkland-islands-malvinas"
                        },
                        new
                        {
                            CountryId = 149,
                            CountryCode = "NE",
                            Name = "Niger",
                            Slug = "niger"
                        },
                        new
                        {
                            CountryId = 150,
                            CountryCode = "NO",
                            Name = "Norway",
                            Slug = "norway"
                        },
                        new
                        {
                            CountryId = 151,
                            CountryCode = "TW",
                            Name = "Taiwan, Republic of China",
                            Slug = "taiwan"
                        },
                        new
                        {
                            CountryId = 152,
                            CountryCode = "GB",
                            Name = "United Kingdom",
                            Slug = "united-kingdom"
                        },
                        new
                        {
                            CountryId = 153,
                            CountryCode = "AG",
                            Name = "Antigua and Barbuda",
                            Slug = "antigua-and-barbuda"
                        },
                        new
                        {
                            CountryId = 154,
                            CountryCode = "SV",
                            Name = "El Salvador",
                            Slug = "el-salvador"
                        },
                        new
                        {
                            CountryId = 155,
                            CountryCode = "GD",
                            Name = "Grenada",
                            Slug = "grenada"
                        },
                        new
                        {
                            CountryId = 156,
                            CountryCode = "LA",
                            Name = "Lao PDR",
                            Slug = "lao-pdr"
                        },
                        new
                        {
                            CountryId = 157,
                            CountryCode = "AU",
                            Name = "Australia",
                            Slug = "australia"
                        },
                        new
                        {
                            CountryId = 158,
                            CountryCode = "CL",
                            Name = "Chile",
                            Slug = "chile"
                        },
                        new
                        {
                            CountryId = 159,
                            CountryCode = "CX",
                            Name = "Christmas Island",
                            Slug = "christmas-island"
                        },
                        new
                        {
                            CountryId = 160,
                            CountryCode = "MS",
                            Name = "Montserrat",
                            Slug = "montserrat"
                        },
                        new
                        {
                            CountryId = 161,
                            CountryCode = "AR",
                            Name = "Argentina",
                            Slug = "argentina"
                        },
                        new
                        {
                            CountryId = 162,
                            CountryCode = "MX",
                            Name = "Mexico",
                            Slug = "mexico"
                        },
                        new
                        {
                            CountryId = 163,
                            CountryCode = "PT",
                            Name = "Portugal",
                            Slug = "portugal"
                        },
                        new
                        {
                            CountryId = 164,
                            CountryCode = "BM",
                            Name = "Bermuda",
                            Slug = "bermuda"
                        },
                        new
                        {
                            CountryId = 165,
                            CountryCode = "EG",
                            Name = "Egypt",
                            Slug = "egypt"
                        },
                        new
                        {
                            CountryId = 166,
                            CountryCode = "ID",
                            Name = "Indonesia",
                            Slug = "indonesia"
                        },
                        new
                        {
                            CountryId = 167,
                            CountryCode = "JE",
                            Name = "Jersey",
                            Slug = "jersey"
                        },
                        new
                        {
                            CountryId = 168,
                            CountryCode = "CR",
                            Name = "Costa Rica",
                            Slug = "costa-rica"
                        },
                        new
                        {
                            CountryId = 169,
                            CountryCode = "CI",
                            Name = "Côte d'Ivoire",
                            Slug = "cote-divoire"
                        },
                        new
                        {
                            CountryId = 170,
                            CountryCode = "LR",
                            Name = "Liberia",
                            Slug = "liberia"
                        },
                        new
                        {
                            CountryId = 171,
                            CountryCode = "MA",
                            Name = "Morocco",
                            Slug = "morocco"
                        },
                        new
                        {
                            CountryId = 172,
                            CountryCode = "MM",
                            Name = "Myanmar",
                            Slug = "myanmar"
                        },
                        new
                        {
                            CountryId = 173,
                            CountryCode = "VU",
                            Name = "Vanuatu",
                            Slug = "vanuatu"
                        },
                        new
                        {
                            CountryId = 174,
                            CountryCode = "AD",
                            Name = "Andorra",
                            Slug = "andorra"
                        },
                        new
                        {
                            CountryId = 175,
                            CountryCode = "KI",
                            Name = "Kiribati",
                            Slug = "kiribati"
                        },
                        new
                        {
                            CountryId = 176,
                            CountryCode = "RW",
                            Name = "Rwanda",
                            Slug = "rwanda"
                        },
                        new
                        {
                            CountryId = 177,
                            CountryCode = "ES",
                            Name = "Spain",
                            Slug = "spain"
                        },
                        new
                        {
                            CountryId = 178,
                            CountryCode = "TO",
                            Name = "Tonga",
                            Slug = "tonga"
                        },
                        new
                        {
                            CountryId = 179,
                            CountryCode = "CH",
                            Name = "Switzerland",
                            Slug = "switzerland"
                        },
                        new
                        {
                            CountryId = 180,
                            CountryCode = "TK",
                            Name = "Tokelau",
                            Slug = "tokelau"
                        },
                        new
                        {
                            CountryId = 181,
                            CountryCode = "GU",
                            Name = "Guam",
                            Slug = "guam"
                        },
                        new
                        {
                            CountryId = 182,
                            CountryCode = "DO",
                            Name = "Dominican Republic",
                            Slug = "dominican-republic"
                        },
                        new
                        {
                            CountryId = 183,
                            CountryCode = "IM",
                            Name = "Isle of Man",
                            Slug = "isle-of-man"
                        },
                        new
                        {
                            CountryId = 184,
                            CountryCode = "MQ",
                            Name = "Martinique",
                            Slug = "martinique"
                        },
                        new
                        {
                            CountryId = 185,
                            CountryCode = "YT",
                            Name = "Mayotte",
                            Slug = "mayotte"
                        },
                        new
                        {
                            CountryId = 186,
                            CountryCode = "RU",
                            Name = "Russian Federation",
                            Slug = "russia"
                        },
                        new
                        {
                            CountryId = 187,
                            CountryCode = "SZ",
                            Name = "Swaziland",
                            Slug = "swaziland"
                        },
                        new
                        {
                            CountryId = 188,
                            CountryCode = "PE",
                            Name = "Peru",
                            Slug = "peru"
                        },
                        new
                        {
                            CountryId = 189,
                            CountryCode = "RE",
                            Name = "Réunion",
                            Slug = "réunion"
                        },
                        new
                        {
                            CountryId = 190,
                            CountryCode = "FR",
                            Name = "France",
                            Slug = "france"
                        },
                        new
                        {
                            CountryId = 191,
                            CountryCode = "GH",
                            Name = "Ghana",
                            Slug = "ghana"
                        },
                        new
                        {
                            CountryId = 192,
                            CountryCode = "GL",
                            Name = "Greenland",
                            Slug = "greenland"
                        },
                        new
                        {
                            CountryId = 193,
                            CountryCode = "HT",
                            Name = "Haiti",
                            Slug = "haiti"
                        },
                        new
                        {
                            CountryId = 194,
                            CountryCode = "KR",
                            Name = "Korea (South)",
                            Slug = "korea-south"
                        },
                        new
                        {
                            CountryId = 195,
                            CountryCode = "PY",
                            Name = "Paraguay",
                            Slug = "paraguay"
                        },
                        new
                        {
                            CountryId = 196,
                            CountryCode = "ET",
                            Name = "Ethiopia",
                            Slug = "ethiopia"
                        },
                        new
                        {
                            CountryId = 197,
                            CountryCode = "SC",
                            Name = "Seychelles",
                            Slug = "seychelles"
                        },
                        new
                        {
                            CountryId = 198,
                            CountryCode = "DK",
                            Name = "Denmark",
                            Slug = "denmark"
                        },
                        new
                        {
                            CountryId = 199,
                            CountryCode = "AT",
                            Name = "Austria",
                            Slug = "austria"
                        },
                        new
                        {
                            CountryId = 200,
                            CountryCode = "BA",
                            Name = "Bosnia and Herzegovina",
                            Slug = "bosnia-and-herzegovina"
                        },
                        new
                        {
                            CountryId = 201,
                            CountryCode = "NI",
                            Name = "Nicaragua",
                            Slug = "nicaragua"
                        },
                        new
                        {
                            CountryId = 202,
                            CountryCode = "SN",
                            Name = "Senegal",
                            Slug = "senegal"
                        },
                        new
                        {
                            CountryId = 203,
                            CountryCode = "MW",
                            Name = "Malawi",
                            Slug = "malawi"
                        },
                        new
                        {
                            CountryId = 204,
                            CountryCode = "PR",
                            Name = "Puerto Rico",
                            Slug = "puerto-rico"
                        },
                        new
                        {
                            CountryId = 205,
                            CountryCode = "KN",
                            Name = "Saint Kitts and Nevis",
                            Slug = "saint-kitts-and-nevis"
                        },
                        new
                        {
                            CountryId = 206,
                            CountryCode = "UZ",
                            Name = "Uzbekistan",
                            Slug = "uzbekistan"
                        },
                        new
                        {
                            CountryId = 207,
                            CountryCode = "AZ",
                            Name = "Azerbaijan",
                            Slug = "azerbaijan"
                        },
                        new
                        {
                            CountryId = 208,
                            CountryCode = "PL",
                            Name = "Poland",
                            Slug = "poland"
                        },
                        new
                        {
                            CountryId = 209,
                            CountryCode = "CZ",
                            Name = "Czech Republic",
                            Slug = "czech-republic"
                        },
                        new
                        {
                            CountryId = 210,
                            CountryCode = "NF",
                            Name = "Norfolk Island",
                            Slug = "norfolk-island"
                        },
                        new
                        {
                            CountryId = 211,
                            CountryCode = "RO",
                            Name = "Romania",
                            Slug = "romania"
                        },
                        new
                        {
                            CountryId = 212,
                            CountryCode = "LC",
                            Name = "Saint Lucia",
                            Slug = "saint-lucia"
                        },
                        new
                        {
                            CountryId = 213,
                            CountryCode = "GS",
                            Name = "South Georgia and the South Sandwich Islands",
                            Slug = "south-georgia-and-the-south-sandwich-islands"
                        },
                        new
                        {
                            CountryId = 214,
                            CountryCode = "BL",
                            Name = "Saint-Barthélemy",
                            Slug = "saint-barthélemy"
                        },
                        new
                        {
                            CountryId = 215,
                            CountryCode = "BD",
                            Name = "Bangladesh",
                            Slug = "bangladesh"
                        },
                        new
                        {
                            CountryId = 216,
                            CountryCode = "CV",
                            Name = "Cape Verde",
                            Slug = "cape-verde"
                        },
                        new
                        {
                            CountryId = 217,
                            CountryCode = "SO",
                            Name = "Somalia",
                            Slug = "somalia"
                        },
                        new
                        {
                            CountryId = 218,
                            CountryCode = "YE",
                            Name = "Yemen",
                            Slug = "yemen"
                        },
                        new
                        {
                            CountryId = 219,
                            CountryCode = "CM",
                            Name = "Cameroon",
                            Slug = "cameroon"
                        },
                        new
                        {
                            CountryId = 220,
                            CountryCode = "SI",
                            Name = "Slovenia",
                            Slug = "slovenia"
                        },
                        new
                        {
                            CountryId = 221,
                            CountryCode = "IT",
                            Name = "Italy",
                            Slug = "italy"
                        },
                        new
                        {
                            CountryId = 222,
                            CountryCode = "VE",
                            Name = "Venezuela (Bolivarian Republic)",
                            Slug = "venezuela"
                        },
                        new
                        {
                            CountryId = 223,
                            CountryCode = "BS",
                            Name = "Bahamas",
                            Slug = "bahamas"
                        },
                        new
                        {
                            CountryId = 224,
                            CountryCode = "HM",
                            Name = "Heard and Mcdonald Islands",
                            Slug = "heard-and-mcdonald-islands"
                        },
                        new
                        {
                            CountryId = 225,
                            CountryCode = "MN",
                            Name = "Mongolia",
                            Slug = "mongolia"
                        },
                        new
                        {
                            CountryId = 226,
                            CountryCode = "PK",
                            Name = "Pakistan",
                            Slug = "pakistan"
                        },
                        new
                        {
                            CountryId = 227,
                            CountryCode = "VG",
                            Name = "British Virgin Islands",
                            Slug = "british-virgin-islands"
                        },
                        new
                        {
                            CountryId = 228,
                            CountryCode = "CK",
                            Name = "Cook Islands",
                            Slug = "cook-islands"
                        },
                        new
                        {
                            CountryId = 229,
                            CountryCode = "IS",
                            Name = "Iceland",
                            Slug = "iceland"
                        },
                        new
                        {
                            CountryId = 230,
                            CountryCode = "TV",
                            Name = "Tuvalu",
                            Slug = "tuvalu"
                        },
                        new
                        {
                            CountryId = 231,
                            CountryCode = "MH",
                            Name = "Marshall Islands",
                            Slug = "marshall-islands"
                        },
                        new
                        {
                            CountryId = 232,
                            CountryCode = "TT",
                            Name = "Trinidad and Tobago",
                            Slug = "trinidad-and-tobago"
                        },
                        new
                        {
                            CountryId = 233,
                            CountryCode = "UY",
                            Name = "Uruguay",
                            Slug = "uruguay"
                        },
                        new
                        {
                            CountryId = 234,
                            CountryCode = "GG",
                            Name = "Guernsey",
                            Slug = "guernsey"
                        },
                        new
                        {
                            CountryId = 235,
                            CountryCode = "DZ",
                            Name = "Algeria",
                            Slug = "algeria"
                        },
                        new
                        {
                            CountryId = 236,
                            CountryCode = "TF",
                            Name = "French Southern Territories",
                            Slug = "french-southern-territories"
                        },
                        new
                        {
                            CountryId = 237,
                            CountryCode = "LB",
                            Name = "Lebanon",
                            Slug = "lebanon"
                        },
                        new
                        {
                            CountryId = 238,
                            CountryCode = "NG",
                            Name = "Nigeria",
                            Slug = "nigeria"
                        },
                        new
                        {
                            CountryId = 239,
                            CountryCode = "HK",
                            Name = "Hong Kong, SAR China",
                            Slug = "hong-kong-sar-china"
                        },
                        new
                        {
                            CountryId = 240,
                            CountryCode = "MF",
                            Name = "Saint-Martin (French part)",
                            Slug = "saint-martin-french-part"
                        },
                        new
                        {
                            CountryId = 241,
                            CountryCode = "AN",
                            Name = "Netherlands Antilles",
                            Slug = "netherlands-antilles"
                        },
                        new
                        {
                            CountryId = 242,
                            CountryCode = "NU",
                            Name = "Niue",
                            Slug = "niue"
                        },
                        new
                        {
                            CountryId = 243,
                            CountryCode = "PA",
                            Name = "Panama",
                            Slug = "panama"
                        },
                        new
                        {
                            CountryId = 244,
                            CountryCode = "NL",
                            Name = "Netherlands",
                            Slug = "netherlands"
                        },
                        new
                        {
                            CountryId = 245,
                            CountryCode = "SA",
                            Name = "Saudi Arabia",
                            Slug = "saudi-arabia"
                        },
                        new
                        {
                            CountryId = 246,
                            CountryCode = "SK",
                            Name = "Slovakia",
                            Slug = "slovakia"
                        },
                        new
                        {
                            CountryId = 247,
                            CountryCode = "AE",
                            Name = "United Arab Emirates",
                            Slug = "united-arab-emirates"
                        },
                        new
                        {
                            CountryId = 248,
                            CountryCode = "NA",
                            Name = "Namibia",
                            Slug = "namibia"
                        });
                });

            modelBuilder.Entity("Covid19_Services_Backend.Models.StatusOfCase", b =>
                {
                    b.Property<int>("StatusOfCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusOfCaseId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusOfCaseId = 1,
                            Name = "confirmed"
                        },
                        new
                        {
                            StatusOfCaseId = 2,
                            Name = "recovered"
                        },
                        new
                        {
                            StatusOfCaseId = 3,
                            Name = "deaths"
                        });
                });

            modelBuilder.Entity("Covid19_Services_Backend.Models.Case", b =>
                {
                    b.HasOne("Covid19_Services_Backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covid19_Services_Backend.Models.StatusOfCase", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
